name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  xmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: korelstar/xmllint-problem-matcher@v1
      - uses: ChristophWurst/xmllint-action@v1.2
        with:
          xml-file: examples/example.sdmn
          xml-schema-file: BPM+/SDMN.xsd